### PR TITLE
Allow Webpack 3.0

### PR DESCRIPTION
**Pull request by ruiaraujo**

### CODE REVIEW

**Comment by Krivega** [comment]
:+1:

**Comment by jakeNiemiec** [comment]
Is this repo inactive? 

//cc @diurnalist

**Comment by carlosrberto** [comment]
when this will be merged?

**Comment by jakeNiemiec** [comment]
@carlosrberto @ruiaraujo @vuzDylan I made a fork for the time being. https://github.com/jakeNiemiec/webpack-chunk-manifest-plugin

**Comment by diurnalist** [comment]
Fixes #41

**Comment by diurnalist** [comment]
Published as 1.1.1, sorry for the delay

**Comment by ruiaraujo** [comment]
@diurnalist NP. Thanks for pulling through.

**Pull request merged**
